// <auto-generated />
namespace TNCVote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedvalidationtophoneandurls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvalidationtophoneandurls));
        
        string IMigrationMetadata.Id
        {
            get { return "201601110506040_added validation to phone and urls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
